# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\chat2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labell = QtWidgets.QLabel(self.centralwidget)
        self.labell.setGeometry(QtCore.QRect(120, 10, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labell.setFont(font)
        self.labell.setObjectName("labell")
        self.txt_input2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_input2.setGeometry(QtCore.QRect(150, 430, 191, 41))
        self.txt_input2.setObjectName("txt_input2")
        self.txt_chat2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_chat2.setEnabled(True)
        self.txt_chat2.setGeometry(QtCore.QRect(150, 100, 191, 271))
        self.txt_chat2.setReadOnly(True)
        self.txt_chat2.setObjectName("txt_chat2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 380, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_send2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send2.setGeometry(QtCore.QRect(190, 490, 93, 28))
        self.btn_send2.setObjectName("btn_send2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labell.setText(_translate("MainWindow", "aes_rsa_socket"))
        self.label_2.setText(_translate("MainWindow", "user_2"))
        self.btn_send2.setText(_translate("MainWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
