# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\chat1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 10, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_input1 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_input1.setGeometry(QtCore.QRect(150, 430, 191, 41))
        self.txt_input1.setObjectName("txt_input1")
        self.txt_chat1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_chat1.setEnabled(True)
        self.txt_chat1.setGeometry(QtCore.QRect(150, 100, 191, 271))
        self.txt_chat1.setReadOnly(True)
        self.txt_chat1.setObjectName("txt_chat1")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(190, 380, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.btn_send1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send1.setGeometry(QtCore.QRect(190, 490, 93, 28))
        self.btn_send1.setObjectName("btn_send1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "aes_rsa_socket"))
        self.label_1.setText(_translate("MainWindow", "user_1"))
        self.btn_send1.setText(_translate("MainWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
