# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(651, 593)
        self.CESAR_CIPHER = QtWidgets.QTabWidget(Form)
        self.CESAR_CIPHER.setGeometry(QtCore.QRect(0, 0, 651, 591))
        self.CESAR_CIPHER.setObjectName("CESAR_CIPHER")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.name_plain_text = QtWidgets.QLabel(self.tab)
        self.name_plain_text.setGeometry(QtCore.QRect(30, 140, 81, 31))
        self.name_plain_text.setObjectName("name_plain_text")
        self.pushButton_Encrypt = QtWidgets.QPushButton(self.tab)
        self.pushButton_Encrypt.setGeometry(QtCore.QRect(180, 460, 75, 23))
        self.pushButton_Encrypt.setObjectName("pushButton_Encrypt")
        self.name_key = QtWidgets.QLabel(self.tab)
        self.name_key.setGeometry(QtCore.QRect(30, 230, 61, 21))
        self.name_key.setObjectName("name_key")
        self.text_cipher_text = QtWidgets.QTextEdit(self.tab)
        self.text_cipher_text.setGeometry(QtCore.QRect(180, 320, 351, 51))
        self.text_cipher_text.setObjectName("text_cipher_text")
        self.text_plain_text = QtWidgets.QTextEdit(self.tab)
        self.text_plain_text.setGeometry(QtCore.QRect(180, 120, 351, 71))
        self.text_plain_text.setObjectName("text_plain_text")
        self.name_cipher_text = QtWidgets.QLabel(self.tab)
        self.name_cipher_text.setGeometry(QtCore.QRect(30, 330, 71, 20))
        self.name_cipher_text.setObjectName("name_cipher_text")
        self.pushButton_Decrypt = QtWidgets.QPushButton(self.tab)
        self.pushButton_Decrypt.setGeometry(QtCore.QRect(460, 460, 75, 23))
        self.pushButton_Decrypt.setObjectName("pushButton_Decrypt")
        self.text_key = QtWidgets.QTextEdit(self.tab)
        self.text_key.setGeometry(QtCore.QRect(180, 230, 351, 51))
        self.text_key.setObjectName("text_key")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(190, 40, 271, 51))
        self.label.setObjectName("label")
        self.CESAR_CIPHER.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.CESAR_CIPHER.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.CESAR_CIPHER.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Caesar Cipher"))
        self.name_plain_text.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Plain Text:</span></p></body></html>"))
        self.pushButton_Encrypt.setText(_translate("Form", "Encrypt"))
        self.name_key.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Key:</span></p></body></html>"))
        self.name_cipher_text.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">CipherText:</span></p></body></html>"))
        self.pushButton_Decrypt.setText(_translate("Form", "  Decrypt"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">CAESAR CIPHER</span></p></body></html>"))
        self.CESAR_CIPHER.setTabText(self.CESAR_CIPHER.indexOf(self.tab), _translate("Form", "Type Here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
